# Development Profile
spring.profiles.active=dev

# Development URLs
auth.service.url=http://localhost:8081

# Development Routes
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[3].uri=http://localhost:8084

# Development Logging
logging.level.com.toolsharing.gateway=DEBUG