# Development Profile
spring.profiles.active=dev

# Development Database
spring.datasource.url=jdbc:postgresql://localhost:5432/user_dev_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Development Logging
logging.level.com.toolsharing.user_service=TRACE

# Auth Service URL (Dev)
auth.service.url=http://localhost:8081