# Server port
server.port=8761

# Application name
spring.application.name=eureka-server

# Eureka instance
eureka.instance.hostname=localhost

# Eureka client settings (server does not register itself)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/

# Eureka server settings
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

# Actuator endpoints
management.endpoints.web.exposure.include=health,info