# Development Profile
spring.profiles.active=dev

# Development Database
spring.datasource.url=jdbc:postgresql://localhost:5434/tool_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# User Service URL (Dev)
user.service.url=http://localhost:8082

# Logging
logging.level.com.toolsharing.tool_service=TRACE